### ISSUE TITLE
Pinoromi RP2350 PGA: PSRAM Support

### ISSUE THREAD

**Issue by Macrosii** [pimoroni/pimoroni-pico-rp2350#7]
Hi
Just wired up my first Pimoroni RP2350 PGA and it is working great with the Version 0.0.6
I dont think the PGA version "pico2b_rp2350" supports the PSRAM as yet.
At some point will you be releasing a version that does ?

Many thanks and regards.

**Comment by Gadgetoid** [comment]
In fact I think the PGA repository should be considered *the* place to get PGA compatible firmware, which is why I haven't added specific builds here. It's currently missing all the batteries-included Pimoroni libraries by default, though, which I should probably change for the sake of anyone just wanting to grab a prebuilt firmware.

**Comment by Gadgetoid** [comment]
This build should work, though be sure to back up first! - https://github.com/pimoroni/pga/actions/runs/10793483972/artifacts/1914387037

**Comment by Macrosii** [comment]
Many thanks Gadgetoid, sorry but I don't get a serial port / repl after uploading this image!

**Comment by Macrosii** [comment]
Ok so came back to this after a few hours with everything powered down.
Now its working, so maybe it was something of the PI USB enumeration side that had got out of kilt.
Many Thanks

**Comment by Gadgetoid** [comment]
Note: I broke saving to flash in that release, should be fixed in https://github.com/pimoroni/pimoroni-pico-rp2350/releases/tag/v0.0.7

**Comment by CHiPs44** [comment]
@Gadgetoid <https://github.com/pimoroni/pimoroni-pico-rp2350/blob/main/README.md> still refers to 0.0.6, did you forgot to push to main?

**Comment by Gadgetoid** [comment]
I have to update the README manually and separate to the release tagging, so yeah I forgot to update it!

**Comment by CHiPs44** [comment]
That's not a big issue, but I downloaded 0.0.6 before lunch and saw this release when I got back to my desk!
